// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NygarnDemo.EFDbContext;

#nullable disable

namespace NygarnDemo.Migrations.HookDb
{
    [DbContext(typeof(HookDbContext))]
    [Migration("20240514204833_AddHookDbContext")]
    partial class AddHookDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NygarnDemo.Models.CrochetHook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Set")
                        .HasColumnType("bit");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hook", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1,
                            Brand = "PetitKnit",
                            Description = "Gode til alt",
                            Material = 0,
                            Name = "Knyt",
                            Price = 49m,
                            Set = true,
                            Size = 7
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2,
                            Brand = "PetitKnit",
                            Description = "Gode til alt",
                            Material = 0,
                            Name = "KnitPro",
                            Price = 149m,
                            Set = false,
                            Size = 3
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1,
                            Brand = "PetitKnit",
                            Description = "Den bedste hækle nål",
                            Material = 0,
                            Name = "KnitPro",
                            Price = 599m,
                            Set = false,
                            Size = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
