// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NygarnDemo.EFDbContext;

#nullable disable

namespace NygarnDemo.Migrations.ToolDb
{
    [DbContext(typeof(ToolDbContext))]
    [Migration("20240513085650_AddToolsTable")]
    partial class AddToolsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NygarnDemo.Models.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tools", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 12,
                            Brand = "PetitKnit",
                            Description = "Rigtig fine små knapper, der passer perfekt til lukningen på en bodystocking",
                            Name = "Babyknap",
                            Price = 30m,
                            Size = "5 mm",
                            Type = "Knapper"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1,
                            Brand = "PetitKnit",
                            Description = "Fuldstændig præcis målebånd",
                            Name = "Målebånd",
                            Price = 25m,
                            Size = "100 cm",
                            Type = "Målebånd"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1,
                            Brand = "Sandnes",
                            Description = "Super blødt bamsefyld til dit næste hækleprojekt",
                            Name = "Bamsefyld",
                            Price = 40m,
                            Size = "100 gram",
                            Type = "Fyld"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
