// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NygarnDemo.EFDbContext;

#nullable disable

namespace NygarnDemo.Migrations.UserDb
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20240516095839_UserTable")]
    partial class UserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NygarnDemo.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("UserName");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserName = "admin",
                            Address = "En sej gade",
                            Email = "nem_hard@garn.dk",
                            Id = 1,
                            LastName = "HARD",
                            Name = "NEM",
                            Password = "AQAAAAIAAYagAAAAEAAMeIGKJFk1yT6hmPGY7/rx+FmjwsH5VIsof66kohgEA3gt4j7X4+Q+yOCWTAjGig==",
                            Phone = "69696969"
                        },
                        new
                        {
                            UserName = "EmmaStrikker123",
                            Address = "Vejgade 1",
                            Email = "emmastrikker@garn.dk",
                            Id = 2,
                            LastName = "Hyttel",
                            Name = "Emma",
                            Password = "AQAAAAIAAYagAAAAEOzOU3S3D8nfS6dien7ag/g3Zums2dxOUOrCn31/sZgx6q5jqwwJ/v8aQily8oQ7Ew==",
                            Phone = "12345678"
                        },
                        new
                        {
                            UserName = "MaiStrikker123",
                            Address = "Vejgade 2",
                            Email = "maistrikker@garn.dk",
                            Id = 3,
                            LastName = "Dinh",
                            Name = "Mai",
                            Password = "AQAAAAIAAYagAAAAEB8pH++OUUonsZM33Ouy7UeIJmq/OPuki+HYMpECc2zdpDBnf8I8GkbuYIa3fk56Jg==",
                            Phone = "23456789"
                        },
                        new
                        {
                            UserName = "NannaHækler123",
                            Address = "Vejgade 3",
                            Email = "nannahækler@garn.dk",
                            Id = 4,
                            LastName = "Rister",
                            Name = "Nanna",
                            Password = "AQAAAAIAAYagAAAAELv+Dmug3b4JaOE/vf8pdY7laP6zMUlVLIegGK3DYqyDWD2HwLvRBBrvF4USFo3JuQ==",
                            Phone = "34567891"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
