// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NygarnDemo.EFDbContext;

#nullable disable

namespace NygarnDemo.Migrations.NeedleDb
{
    [DbContext(typeof(NeedleDbContext))]
    [Migration("20240516090924_NeedleTable")]
    partial class NeedleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NygarnDemo.Models.KnittingNeedle", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Set")
                        .HasColumnType("bit");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("KnittingNeedles", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Amount = 2,
                            Brand = "PetitKnit",
                            Description = "Gode til alt",
                            Material = 0,
                            Name = "KnitPro",
                            Price = 149m,
                            Set = true,
                            Size = 3,
                            Type = 1
                        },
                        new
                        {
                            ProductId = 2,
                            Amount = 2,
                            Brand = "PetitKnit",
                            Description = "Dejlig store",
                            Material = 2,
                            Name = "Hot",
                            Price = 499m,
                            Set = true,
                            Size = 5,
                            Type = 3
                        },
                        new
                        {
                            ProductId = 3,
                            Amount = 2,
                            Brand = "PetitKnit",
                            Description = "Gode til alt",
                            Material = 0,
                            Name = "KnitPro",
                            Price = 140m,
                            Set = true,
                            Size = 3,
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
