// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NygarnDemo.EFDbContext;

#nullable disable

namespace NygarnDemo.Migrations
{
    [DbContext(typeof(YarnDbContext))]
    [Migration("20240507205714_NygarnDemo")]
    partial class NygarnDemo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NygarnDemo.Models.Yarn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("Brand")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("KnittingTension")
                        .HasColumnType("int");

                    b.Property<bool>("MachineWash")
                        .HasColumnType("bit");

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<int>("Yardage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("YarnProducts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10,
                            Brand = 0,
                            Color = 0,
                            Description = "Meget luksus garn, ikke egnet til påklædning.",
                            KnittingTension = 0,
                            MachineWash = false,
                            Material = 0,
                            Name = "Luksus garn",
                            Price = 99m,
                            Size = 2,
                            Weight = 100,
                            Yardage = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 10,
                            Brand = 0,
                            Color = 0,
                            Description = "Meget luksus garn, ikke egnet til påklædning.",
                            KnittingTension = 0,
                            MachineWash = false,
                            Material = 0,
                            Name = "Saga",
                            Price = 49m,
                            Size = 2,
                            Weight = 100,
                            Yardage = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1,
                            Brand = 0,
                            Color = 9,
                            Description = "Vildt lækkert mohair garn til din næste sweater",
                            KnittingTension = 1,
                            MachineWash = true,
                            Material = 2,
                            Name = "MyHair",
                            Price = 79m,
                            Size = 1,
                            Weight = 50,
                            Yardage = 0
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1,
                            Brand = 1,
                            Color = 9,
                            Description = "Vildt lækkert alpakka garn til dit næste tørklæde",
                            KnittingTension = 2,
                            MachineWash = true,
                            Material = 0,
                            Name = "MaLamaa",
                            Price = 69m,
                            Size = 3,
                            Weight = 50,
                            Yardage = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1,
                            Brand = 1,
                            Color = 0,
                            Description = "Vildt lækkert silke garn til dit næste hårbånd",
                            KnittingTension = 3,
                            MachineWash = false,
                            Material = 1,
                            Name = "SlikkeSilke",
                            Price = 75m,
                            Size = 5,
                            Weight = 50,
                            Yardage = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
